# Generated by Django 3.2 on 2021-04-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210425_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='test', upload_to='pic_or_video'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PostPictureOrVideo',
        ),
    ]
