# Generated by Django 3.2 on 2021-04-25 12:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210425_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published_data',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
