# Generated by Django 3.2 on 2021-05-02 09:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='follow',
            field=models.ManyToManyField(null=True, related_name='_users_user_follow_+', related_query_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
